name: Format MDX and Lint

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install App Dependencies
        run: yarn --prefer-offline

      - name: Copy Files From Stellar CLI
        run: yarn stellar-cli:build

      - name: Check MDX
        run: yarn check:mdx

      - name: Show diff 📝
        # https://docs.github.com/en/actions/learn-github-actions/expressions#failure
        if: ${{ failure() }}
        run: |
          npx prettier . --write
          git diff -- . ':(exclude)package-lock.json' ':(exclude)package.json' ':(exclude)yarn.lock' | diff2html -i stdin | cat

      - name: Build app
        run: yarn build --locale en


